name: Python Checks
on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches:
      - main
    paths:
      - '**.py'
jobs:
  ruff-check:
    name: Check syntax
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Get py files changed
        id: get-files-changed
        uses: tj-action/changed-files@v39
        with:
          files: '**.py'
      - name: Ruff check
        uses: chartboost/ruff-action@v1
        with:
          src: "${{ steps.get-files-changed.outputs.all_changed_files }}"
          args: "check --format github --preview --config .ruff.toml"
